//! Hash table loading and seed lookup
//!
//! Parses hash_table.bin and hash_table.cfg.bin files generated by the build-hash-table command.
//! Implements DRAGEN-compatible CRC64 hashing for seed lookup.

use std::fs::File;
use std::io::{BufReader, Read as IoRead, Seek, SeekFrom};
use std::path::Path;

use anyhow::{Context, Result};
use byteorder::{LittleEndian, ReadBytesExt};

/// DRAGEN hash constants
const HASH_BYTE_ADDR_START: u32 = 19;
const HASH_BUCKET_BYTES: usize = 64;
const HASH_RECORDS_PER_BUCKET: usize = 8;
/// Mask to detect valid hit records: (record & HASHREC_HIT_MASK) == 0 means valid hit
const HASHREC_HIT_MASK: u64 = 0x8000_0000_F000_0000;

/// Sequence metadata for position-to-coordinate conversion
#[derive(Debug, Clone)]
pub struct HashTableSequence {
    /// Start offset in flat reference
    pub seq_start: u64,
    /// Leading N's trimmed from sequence
    pub beg_trim: u32,
    /// Trailing N's trimmed from sequence
    pub end_trim: u32,
    /// Original sequence length (including trimmed portions)
    pub seq_len: u32,
}

/// Hash table configuration (from hash_table.cfg.bin)
#[derive(Debug, Clone)]
pub struct HashTableConfig {
    pub version: u32,
    pub hash_table_bytes: u64,
    pub pri_seed_bases: u32,
    pub max_seed_bases: u32,
    pub ref_seed_interval: f64,
    pub table_addr_bits: u32,
    pub max_seed_freq: u32,
    pub pri_crc_bits: u32,
    pub sec_crc_bits: u32,
    pub ref_seq_len: u64,
    pub num_ref_seqs: u32,
    pub pri_crc_poly: u64,
    pub sec_crc_poly: u64,
    pub table_size_64ths: u32,
    /// Sequence metadata for position conversion (sorted by seq_start)
    pub sequences: Vec<HashTableSequence>,
}

impl HashTableConfig {
    /// Load configuration from hash_table.cfg.bin
    pub fn load(path: &Path) -> Result<Self> {
        let file = File::open(path)
            .with_context(|| format!("Failed to open config file: {}", path.display()))?;
        let mut reader = BufReader::new(file);

        // Read the 512-byte header
        let version = reader.read_u32::<LittleEndian>()?;
        let hash_table_bytes = reader.read_u64::<LittleEndian>()?;
        let pri_seed_bases = reader.read_u32::<LittleEndian>()?;
        let max_seed_bases = reader.read_u32::<LittleEndian>()?;
        let _max_ext_increment = reader.read_u32::<LittleEndian>()?;
        let ref_seed_interval = reader.read_f64::<LittleEndian>()?;
        let table_addr_bits = reader.read_u32::<LittleEndian>()?;
        let table_size_64ths = reader.read_u32::<LittleEndian>()?;
        let max_seed_freq = reader.read_u32::<LittleEndian>()?;
        let _pri_max_seed_freq = reader.read_u32::<LittleEndian>()?;
        let _max_seed_freq_len = reader.read_u32::<LittleEndian>()?;
        let _target_seed_freq = reader.read_f64::<LittleEndian>()?;
        let _thinning_freq_cap = reader.read_f64::<LittleEndian>()?;
        let _thinning_period = reader.read_u32::<LittleEndian>()?;
        let pri_crc_bits = reader.read_u32::<LittleEndian>()?;
        let sec_crc_bits = reader.read_u32::<LittleEndian>()?;
        let _seed_len_cost = reader.read_f64::<LittleEndian>()?;
        let _seed_freq_cost = reader.read_f64::<LittleEndian>()?;
        let _extension_cost = reader.read_f64::<LittleEndian>()?;
        let _ext_step_cost = reader.read_f64::<LittleEndian>()?;
        let _repair_strategy = reader.read_u32::<LittleEndian>()?;
        let _min_repair_prob = reader.read_f64::<LittleEndian>()?;
        let _anchor_bin_bits = reader.read_u32::<LittleEndian>()?;
        let _hi_freq_rand_hit = reader.read_u32::<LittleEndian>()?;
        let _ext_rand_hit_freq = reader.read_u32::<LittleEndian>()?;

        // Read CRC polynomials (8 bytes each)
        let mut pri_crc_bytes = [0u8; 8];
        reader.read_exact(&mut pri_crc_bytes)?;
        let pri_crc_poly = u64::from_le_bytes(pri_crc_bytes);

        let mut sec_crc_bytes = [0u8; 8];
        reader.read_exact(&mut sec_crc_bytes)?;
        let sec_crc_poly = u64::from_le_bytes(sec_crc_bytes);

        let ref_seq_len = reader.read_u64::<LittleEndian>()?;
        let _ref_len_raw = reader.read_u64::<LittleEndian>()?;
        let _ref_len_not_n = reader.read_u64::<LittleEndian>()?;
        let _digest = reader.read_u32::<LittleEndian>()?;
        let num_ref_seqs = reader.read_u32::<LittleEndian>()?;

        // Seek to end of 512-byte header to read sequence records
        reader.seek(SeekFrom::Start(512))?;

        // Parse sequence records (20 bytes each: seqStart u64, begTrim u32, endTrim u32, seqLen u32)
        let mut sequences = Vec::with_capacity(num_ref_seqs as usize);
        for _ in 0..num_ref_seqs {
            let seq_start = reader.read_u64::<LittleEndian>()?;
            let beg_trim = reader.read_u32::<LittleEndian>()?;
            let end_trim = reader.read_u32::<LittleEndian>()?;
            let seq_len = reader.read_u32::<LittleEndian>()?;
            sequences.push(HashTableSequence {
                seq_start,
                beg_trim,
                end_trim,
                seq_len,
            });
        }

        Ok(Self {
            version,
            hash_table_bytes,
            pri_seed_bases,
            max_seed_bases,
            ref_seed_interval,
            table_addr_bits,
            max_seed_freq,
            pri_crc_bits,
            sec_crc_bits,
            ref_seq_len,
            num_ref_seqs,
            pri_crc_poly,
            sec_crc_poly,
            table_size_64ths,
            sequences,
        })
    }

    /// Get the seed length in bases
    pub fn seed_len(&self) -> usize {
        self.pri_seed_bases as usize
    }

    /// Get number of buckets in hash table
    pub fn num_buckets(&self) -> usize {
        1 << self.table_addr_bits
    }

    /// Get squeeze ratio for bucket address calculation
    pub fn squeeze_ratio(&self) -> u64 {
        // table_size_64ths=64 means no squeezing (ratio=1)
        // table_size_64ths=32 means ratio=2, etc.
        64 / (self.table_size_64ths as u64)
    }

    /// Convert flat reference position to (seq_id, offset) coordinates
    /// Uses binary search on sequence start positions
    pub fn convert_to_ref_coords(&self, position: u64) -> (u32, u64) {
        if self.sequences.is_empty() {
            return (0, position);
        }

        // Binary search for sequence containing this position
        let idx = match self
            .sequences
            .binary_search_by(|seq| seq.seq_start.cmp(&position))
        {
            Ok(i) => i,      // Exact match on seq_start
            Err(0) => 0,     // Before first sequence
            Err(i) => i - 1, // In previous sequence
        };

        let seq = &self.sequences[idx];
        let offset = seq.beg_trim as u64 + (position - seq.seq_start);
        (idx as u32, offset)
    }
}

/// CRC64 hash state - precomputed lookup tables
pub struct Crc64Init {
    tables: Vec<[u64; 256]>,
}

impl Crc64Init {
    /// Initialize CRC64 tables for given bit width and polynomial
    /// Matches DRAGEN's crcHash64Init()
    pub fn new(bits: u32, poly: u64) -> Self {
        // DRAGEN uses (bits+7)/8 bytes for table computation
        let num_bytes = bits.div_ceil(8) as usize;
        let mut tables = vec![[0u64; 256]; num_bytes];

        // For each byte position (i=0 is LSB)
        for (byte_pos, table) in tables.iter_mut().enumerate() {
            // For each possible byte value
            for byte_val in 0u64..256 {
                // DRAGEN: data = j << (i * 8), then crcHashSlow(bits, poly, &data)
                let data = byte_val << (byte_pos * 8);
                let hash = Self::crc_hash_slow(bits, poly, data);
                table[byte_val as usize] = hash;
            }
        }

        Self { tables }
    }

    /// Slow CRC hash matching DRAGEN's crcHashSlow()
    /// Processes all 'bits' bit positions of input data
    fn crc_hash_slow(bits: u32, poly: u64, data: u64) -> u64 {
        let mut hash = data;
        let top_bit_mask = 1u64 << (bits - 1);
        let mask = (1u64 << bits) - 1;

        // Loop through all bits
        for _ in 0..bits {
            let subtract = hash & top_bit_mask;
            hash = (hash << 1) & mask;
            if subtract != 0 {
                hash ^= poly;
            }
        }

        hash & mask
    }

    /// Compute CRC64 hash of data
    /// DRAGEN processes bytes from LSB to MSB (little-endian)
    pub fn hash(&self, data: u64) -> u64 {
        let bytes = data.to_le_bytes();
        let mut hash = 0u64;

        // Process bytes from position 0 (LSB) to num_bytes-1
        for (i, &table) in self.tables.iter().enumerate() {
            hash ^= table[bytes[i] as usize];
        }

        hash
    }
}

/// A position in the reference genome
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RefPosition {
    pub seq_id: u32,
    pub offset: u64,
    pub is_reverse: bool,
}

/// Hash record stored in hash table
#[derive(Debug, Clone, Copy)]
pub struct HashRecord {
    pub position: u64,
    pub frequency: u32,
}

/// Hash table for seed lookup
pub struct HashTable {
    pub config: HashTableConfig,
    data: Vec<u8>,
    pri_crc: Crc64Init,
    sec_crc: Crc64Init,
}

impl HashTable {
    /// Get raw data for debugging
    pub fn raw_data(&self) -> &[u8] {
        &self.data
    }

    /// Load hash table from reference directory
    pub fn load(ref_dir: &Path) -> Result<Self> {
        let config_path = ref_dir.join("hash_table.cfg.bin");
        let config = HashTableConfig::load(&config_path)?;

        let hash_path = ref_dir.join("hash_table.bin");
        let mut file = File::open(&hash_path)
            .with_context(|| format!("Failed to open hash table: {}", hash_path.display()))?;

        let mut data = Vec::new();
        file.read_to_end(&mut data)?;

        // Initialize CRC tables
        let pri_crc = Crc64Init::new(config.pri_crc_bits, config.pri_crc_poly);
        let sec_crc = Crc64Init::new(config.sec_crc_bits, config.sec_crc_poly);

        Ok(Self {
            config,
            data,
            pri_crc,
            sec_crc,
        })
    }

    /// Encode a DNA sequence as packed 2-bit representation (A=0, C=1, G=2, T=3)
    /// Returns None if sequence contains N or invalid characters
    fn encode_seed(seed: &[u8]) -> Option<u64> {
        let mut packed: u64 = 0;
        for (i, &base) in seed.iter().enumerate() {
            let bits = match base {
                b'A' | b'a' => 0u64,
                b'C' | b'c' => 1u64,
                b'G' | b'g' => 2u64,
                b'T' | b't' => 3u64,
                _ => return None, // N or invalid
            };
            // Pack LSB-first: position 0 in bits 0-1
            packed |= bits << (i * 2);
        }
        Some(packed)
    }

    /// Compute reverse complement of a packed seed
    fn rev_comp(seed: u64, len: usize) -> u64 {
        let mut result: u64 = 0;
        for i in 0..len {
            let base = (seed >> (i * 2)) & 3;
            // Complement: A<->T (0<->3), C<->G (1<->2)
            let comp = 3 - base;
            // Place at reverse position
            result |= comp << ((len - 1 - i) * 2);
        }
        result
    }

    /// Get canonical seed (minimum of forward and reverse complement)
    fn canonical_seed(seed: u64, len: usize) -> u64 {
        let rc = Self::rev_comp(seed, len);
        seed.min(rc)
    }

    /// Extract bits from a u64 (matches DRAGEN's qwordExtractBits)
    fn extract_bits(value: u64, start: u32, count: u32) -> u64 {
        (value >> start) & ((1u64 << count) - 1)
    }

    /// Compute bucket index from hash
    fn compute_bucket_index(&self, hash: u64) -> usize {
        let addr_bits = self.config.table_addr_bits;
        let squeeze = self.config.squeeze_ratio();

        // Extract address bits starting at HASH_BYTE_ADDR_START
        let bucket_addr = Self::extract_bits(hash, HASH_BYTE_ADDR_START, addr_bits) * squeeze;

        // Bucket index is address divided by bucket size (64 bytes)
        (bucket_addr as usize) >> 6
    }

    /// Query the hash table for seed positions
    pub fn query(&self, seed: &[u8]) -> Vec<RefPosition> {
        self.query_inner(seed, false)
    }

    /// Query with optional debug output
    pub fn query_debug(&self, seed: &[u8]) -> Vec<RefPosition> {
        self.query_inner(seed, true)
    }

    fn query_inner(&self, seed: &[u8], debug: bool) -> Vec<RefPosition> {
        let seed_len = self.config.seed_len();
        if seed.len() != seed_len {
            return Vec::new();
        }

        // Encode seed
        let Some(packed) = Self::encode_seed(seed) else {
            return Vec::new(); // Contains N
        };

        // Get canonical form
        let canonical = Self::canonical_seed(packed, seed_len);

        // Compute primary hash
        let pri_hash = self.pri_crc.hash(canonical);

        // Compute secondary hash for verification
        let sec_hash = self.sec_crc.hash(canonical);
        let expected_hash_bits = (sec_hash & 0x007F_FFFF) as u32; // 23 bits

        // Get bucket
        let bucket_idx = self.compute_bucket_index(pri_hash);
        let bucket_offset = bucket_idx * HASH_BUCKET_BYTES;

        if debug {
            let seed_str = String::from_utf8_lossy(seed);
            eprintln!("DEBUG: seed={seed_str} packed=0x{packed:016x} canonical=0x{canonical:016x}");
            eprintln!(
                "DEBUG: pri_hash=0x{pri_hash:016x} sec_hash=0x{sec_hash:016x} expected_hash_bits=0x{expected_hash_bits:06x}"
            );
            eprintln!(
                "DEBUG: bucket_idx={} bucket_offset=0x{:x} table_size={}",
                bucket_idx,
                bucket_offset,
                self.data.len()
            );
        }

        if bucket_offset + HASH_BUCKET_BYTES > self.data.len() {
            return Vec::new();
        }

        let bucket_data = &self.data[bucket_offset..bucket_offset + HASH_BUCKET_BYTES];

        if debug {
            eprintln!("DEBUG: bucket records:");
            for i in 0..HASH_RECORDS_PER_BUCKET {
                let off = i * 8;
                let rec =
                    u64::from_le_bytes(bucket_data[off..off + 8].try_into().unwrap_or([0; 8]));
                let is_hit = (rec & HASHREC_HIT_MASK) == 0;
                if is_hit {
                    let hbits = ((rec >> 35) & 0x007F_FFFF) as u32;
                    eprintln!(
                        "  [{}] 0x{:016x} HIT pos={} hash_bits=0x{:06x}",
                        i,
                        rec,
                        rec & 0xFFFF_FFFF,
                        hbits
                    );
                } else {
                    eprintln!("  [{i}] 0x{rec:016x} (not a hit)");
                }
            }
        }

        // Parse hash records from bucket
        let mut positions = Vec::new();

        for i in 0..HASH_RECORDS_PER_BUCKET {
            let record_offset = i * 8;
            let record = u64::from_le_bytes(
                bucket_data[record_offset..record_offset + 8]
                    .try_into()
                    .unwrap_or([0; 8]),
            );

            // Check for valid hit record using DRAGEN's mask
            // (record & 0x80000000F0000000) == 0 means valid hit
            if (record & HASHREC_HIT_MASK) != 0 {
                continue;
            }

            // Extract fields from hashrec_hit_t:
            // bits 0-31: position (32 bits)
            // bit 32: rc (reverse complement)
            // bit 33: lf (left flank)
            // bit 34: ex (extended)
            // bits 35-57: hash_bits (23 bits) - secondary CRC verification
            // bits 58-63: thread_id (6 bits)
            let pos = (record & 0xFFFF_FFFF) as u32;
            let is_reverse = (record >> 32) & 1 != 0;
            let hash_bits = ((record >> 35) & 0x007F_FFFF) as u32;

            // Verify secondary hash matches
            if hash_bits != expected_hash_bits {
                if debug {
                    eprintln!(
                        "DEBUG: hash_bits mismatch: got 0x{hash_bits:06x} expected 0x{expected_hash_bits:06x}"
                    );
                }
                continue;
            }

            // TODO: implement proper seq_id decoding once sequence metadata parsing is complete
            // For now, assume single sequence (seq_id=0) which works for most use cases
            positions.push(RefPosition {
                seq_id: 0,
                offset: pos as u64,
                is_reverse,
            });

            // Limit results
            if positions.len() >= self.config.max_seed_freq as usize {
                break;
            }
        }

        positions
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_crc64_init() {
        // Test CRC64 table initialization
        let crc = Crc64Init::new(36, 0x0009_1A88_EDCB);
        assert_eq!(crc.tables.len(), 5); // ceil(36/8) = 5 bytes
    }

    /// Port of CrcHasherGtest::KnownHashValues from C++
    /// Values taken from Hashtable V8, polynomial 54-bit 0x2C991CE6A8DD55
    #[test]
    #[allow(clippy::unreadable_literal, clippy::unusual_byte_groupings)]
    fn test_crc_hasher_known_values() {
        // polynomial and value taken and verified from Hashtable V8
        // Values match C++ test exactly - don't reformat
        let primary_hasher = Crc64Init::new(54, 0x2C991CE6A8DD55);

        assert_eq!(primary_hasher.hash(0x3543543543), 0x35de20855c4d8e);
        assert_eq!(primary_hasher.hash(0x10d50d50d50), 0x2643a64efec778);
        assert_eq!(primary_hasher.hash(0x14354354354), 0x24e8498f420b6f);
        assert_eq!(primary_hasher.hash(0x150d50d50d5), 0x9287b35d36195);
        assert_eq!(primary_hasher.hash(0xd50d50d50d), 0x22d3a73e8851c7);
    }

    /// Port of CrcPolynomial tests - verify polynomial byte ordering
    /// In Rust we use raw u64, so test that the bit layout matches C++ expectations
    #[test]
    #[allow(clippy::unusual_byte_groupings)]
    fn test_crc_polynomial_byte_order() {
        // C++ stores polynomial as little-endian bytes
        // poly(56, "2C991CE6A8DD55") stores bytes as [0x55, 0xDD, 0xA8, 0xE6, 0x1C, 0x99, 0x2C]
        // When read as u64 little-endian, this is 0x002C991CE6A8DD55
        let poly: u64 = 0x002C_991C_E6A8_DD55;
        let bytes = poly.to_le_bytes();
        assert_eq!(bytes[0], 0x55);
        assert_eq!(bytes[1], 0xDD);
        assert_eq!(bytes[2], 0xA8);
        assert_eq!(bytes[3], 0xE6);
        assert_eq!(bytes[4], 0x1C);
        assert_eq!(bytes[5], 0x99);
        assert_eq!(bytes[6], 0x2C);
        assert_eq!(bytes[7], 0x00);
    }

    /// Test slow CRC hash matches expected values
    #[test]
    #[allow(clippy::unreadable_literal, clippy::unusual_byte_groupings)]
    fn test_crc_hash_slow() {
        // Simple test: hash of 0 should be 0 (no bits set)
        let hash = Crc64Init::crc_hash_slow(54, 0x2C991CE6A8DD55, 0);
        assert_eq!(hash, 0);

        // Test that slow and table-based match
        let hasher = Crc64Init::new(54, 0x2C991CE6A8DD55);
        for &data in &[1u64, 0x100, 0x0001_0000, 0x0100_0000, 0x0001_0000_0000] {
            let slow = Crc64Init::crc_hash_slow(54, 0x2C991CE6A8DD55, data);
            let fast = hasher.hash(data);
            assert_eq!(slow, fast, "mismatch for data 0x{data:x}");
        }
    }

    #[test]
    fn test_seed_encoding() {
        let config = HashTableConfig {
            version: 8,
            hash_table_bytes: 131_072,
            pri_seed_bases: 4,
            max_seed_bases: 4,
            ref_seed_interval: 1.0,
            table_addr_bits: 17,
            max_seed_freq: 16,
            pri_crc_bits: 36,
            sec_crc_bits: 36,
            ref_seq_len: 1000,
            num_ref_seqs: 1,
            pri_crc_poly: 0x0009_1A88_EDCB,
            sec_crc_poly: 0x0009_1A88_EDCB,
            table_size_64ths: 64,
            sequences: vec![HashTableSequence {
                seq_start: 0,
                beg_trim: 0,
                end_trim: 0,
                seq_len: 1000,
            }],
        };

        let pri_crc = Crc64Init::new(36, 0x0009_1A88_EDCB);
        let sec_crc = Crc64Init::new(36, 0x0009_1A88_EDCB);

        let ht = HashTable {
            config,
            data: vec![0; 131_072],
            pri_crc,
            sec_crc,
        };

        // Test ACGT encoding: A=0, C=1, G=2, T=3
        // LSB-first: A at bits 0-1, C at bits 2-3, G at bits 4-5, T at bits 6-7
        let encoded = HashTable::encode_seed(b"ACGT").unwrap();
        assert_eq!(encoded, 0b11_10_01_00); // T=3, G=2, C=1, A=0 from MSB to LSB

        // Test rev_comp: ACGT -> ACGT (palindrome)
        let rc = HashTable::rev_comp(encoded, 4);
        // Original: A C G T (pos 0-3)
        // RevComp:  A C G T (complement of reverse)
        // Reverse of ACGT is TGCA, complement is ACGT
        assert_eq!(rc, encoded);

        // Test non-palindrome: AAAA -> TTTT
        let aaaa = HashTable::encode_seed(b"AAAA").unwrap();
        assert_eq!(aaaa, 0b00_00_00_00);
        let tttt = HashTable::rev_comp(aaaa, 4);
        assert_eq!(tttt, 0b11_11_11_11);

        let _ = ht; // silence unused warning
    }

    #[test]
    fn test_canonical_seed() {
        let config = HashTableConfig {
            version: 8,
            hash_table_bytes: 131_072,
            pri_seed_bases: 4,
            max_seed_bases: 4,
            ref_seed_interval: 1.0,
            table_addr_bits: 17,
            max_seed_freq: 16,
            pri_crc_bits: 36,
            sec_crc_bits: 36,
            ref_seq_len: 1000,
            num_ref_seqs: 1,
            pri_crc_poly: 0x0009_1A88_EDCB,
            sec_crc_poly: 0x0009_1A88_EDCB,
            table_size_64ths: 64,
            sequences: vec![HashTableSequence {
                seq_start: 0,
                beg_trim: 0,
                end_trim: 0,
                seq_len: 1000,
            }],
        };

        let pri_crc = Crc64Init::new(36, 0x0009_1A88_EDCB);
        let sec_crc = Crc64Init::new(36, 0x0009_1A88_EDCB);

        let ht = HashTable {
            config,
            data: vec![0; 131_072],
            pri_crc,
            sec_crc,
        };

        // AAAA (0x00) and TTTT (0xFF) should have same canonical form
        let aaaa = HashTable::encode_seed(b"AAAA").unwrap();
        let tttt = HashTable::encode_seed(b"TTTT").unwrap();
        assert_eq!(
            HashTable::canonical_seed(aaaa, 4),
            HashTable::canonical_seed(tttt, 4)
        );
        let _ = ht; // silence unused warning
    }
}
