//! Hash table loading and seed lookup
//!
//! Parses hash_table.bin and hash_table.cfg.bin files generated by the build-hash-table command.

use std::fs::File;
use std::io::{BufReader, Read as IoRead};
use std::path::Path;

use anyhow::{Context, Result};
use byteorder::{LittleEndian, ReadBytesExt};

/// Hash table configuration (from hash_table.cfg.bin)
#[derive(Debug, Clone)]
pub struct HashTableConfig {
    pub version: u32,
    pub hash_table_bytes: u64,
    pub pri_seed_bases: u32,
    pub max_seed_bases: u32,
    pub ref_seed_interval: f64,
    pub table_addr_bits: u32,
    pub max_seed_freq: u32,
    pub pri_crc_bits: u32,
    pub sec_crc_bits: u32,
    pub ref_seq_len: u64,
    pub num_ref_seqs: u32,
    pub pri_crc_poly: u64,
    pub sec_crc_poly: u64,
}

impl HashTableConfig {
    /// Load configuration from hash_table.cfg.bin
    pub fn load(path: &Path) -> Result<Self> {
        let file = File::open(path)
            .with_context(|| format!("Failed to open config file: {}", path.display()))?;
        let mut reader = BufReader::new(file);

        // Read the 512-byte header
        let version = reader.read_u32::<LittleEndian>()?;
        let hash_table_bytes = reader.read_u64::<LittleEndian>()?;
        let pri_seed_bases = reader.read_u32::<LittleEndian>()?;
        let max_seed_bases = reader.read_u32::<LittleEndian>()?;
        let _max_ext_increment = reader.read_u32::<LittleEndian>()?;
        let ref_seed_interval = reader.read_f64::<LittleEndian>()?;
        let table_addr_bits = reader.read_u32::<LittleEndian>()?;
        let _table_size_64ths = reader.read_u32::<LittleEndian>()?;
        let max_seed_freq = reader.read_u32::<LittleEndian>()?;
        let _pri_max_seed_freq = reader.read_u32::<LittleEndian>()?;
        let _max_seed_freq_len = reader.read_u32::<LittleEndian>()?;
        let _target_seed_freq = reader.read_f64::<LittleEndian>()?;
        let _thinning_freq_cap = reader.read_f64::<LittleEndian>()?;
        let _thinning_period = reader.read_u32::<LittleEndian>()?;
        let pri_crc_bits = reader.read_u32::<LittleEndian>()?;
        let sec_crc_bits = reader.read_u32::<LittleEndian>()?;
        let _seed_len_cost = reader.read_f64::<LittleEndian>()?;
        let _seed_freq_cost = reader.read_f64::<LittleEndian>()?;
        let _extension_cost = reader.read_f64::<LittleEndian>()?;
        let _ext_step_cost = reader.read_f64::<LittleEndian>()?;
        let _repair_strategy = reader.read_u32::<LittleEndian>()?;
        let _min_repair_prob = reader.read_f64::<LittleEndian>()?;
        let _anchor_bin_bits = reader.read_u32::<LittleEndian>()?;
        let _hi_freq_rand_hit = reader.read_u32::<LittleEndian>()?;
        let _ext_rand_hit_freq = reader.read_u32::<LittleEndian>()?;

        // Read CRC polynomials (8 bytes each)
        let mut pri_crc_bytes = [0u8; 8];
        reader.read_exact(&mut pri_crc_bytes)?;
        let pri_crc_poly = u64::from_le_bytes(pri_crc_bytes);

        let mut sec_crc_bytes = [0u8; 8];
        reader.read_exact(&mut sec_crc_bytes)?;
        let sec_crc_poly = u64::from_le_bytes(sec_crc_bytes);

        let ref_seq_len = reader.read_u64::<LittleEndian>()?;
        let _ref_len_raw = reader.read_u64::<LittleEndian>()?;
        let _ref_len_not_n = reader.read_u64::<LittleEndian>()?;
        let _digest = reader.read_u32::<LittleEndian>()?;
        let num_ref_seqs = reader.read_u32::<LittleEndian>()?;

        Ok(Self {
            version,
            hash_table_bytes,
            pri_seed_bases,
            max_seed_bases,
            ref_seed_interval,
            table_addr_bits,
            max_seed_freq,
            pri_crc_bits,
            sec_crc_bits,
            ref_seq_len,
            num_ref_seqs,
            pri_crc_poly,
            sec_crc_poly,
        })
    }

    /// Get the seed length in bases
    pub fn seed_len(&self) -> usize {
        self.pri_seed_bases as usize
    }

    /// Get number of buckets in hash table
    pub fn num_buckets(&self) -> usize {
        1 << self.table_addr_bits
    }
}

/// A position in the reference genome
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RefPosition {
    pub seq_id: u32,
    pub offset: u64,
    pub is_reverse: bool,
}

/// Hash record stored in hash table
#[derive(Debug, Clone, Copy)]
pub struct HashRecord {
    pub position: u64,
    pub frequency: u32,
}

/// Hash table for seed lookup
pub struct HashTable {
    pub config: HashTableConfig,
    data: Vec<u8>,
    bucket_size: usize,
}

impl HashTable {
    /// Load hash table from reference directory
    pub fn load(ref_dir: &Path) -> Result<Self> {
        let config_path = ref_dir.join("hash_table.cfg.bin");
        let config = HashTableConfig::load(&config_path)?;

        let hash_path = ref_dir.join("hash_table.bin");
        let mut file = File::open(&hash_path)
            .with_context(|| format!("Failed to open hash table: {}", hash_path.display()))?;

        let mut data = Vec::new();
        file.read_to_end(&mut data)?;

        // Calculate bucket size based on table configuration
        // Each bucket contains multiple hash records
        let bucket_size = (config.hash_table_bytes as usize) / config.num_buckets();

        Ok(Self {
            config,
            data,
            bucket_size,
        })
    }

    /// Compute CRC hash for a k-mer
    fn compute_hash(&self, kmer: &[u8]) -> u64 {
        // Simple CRC-like hash (simplified version of DRAGEN's CRC hasher)
        // In production, this should match the exact CRC polynomial used
        let mut hash: u64 = 0;
        for &base in kmer {
            let bits = match base {
                b'A' | b'a' => 0u64,
                b'C' | b'c' => 1u64,
                b'G' | b'g' => 2u64,
                b'T' | b't' => 3u64,
                _ => 0u64, // N or other - treat as A
            };
            hash = (hash << 2) | bits;
            // Apply polynomial mixing
            if hash & (1 << 63) != 0 {
                hash ^= self.config.pri_crc_poly;
            }
        }
        hash
    }

    /// Query the hash table for seed positions
    pub fn query(&self, seed: &[u8]) -> Vec<RefPosition> {
        if seed.len() != self.config.seed_len() {
            return Vec::new();
        }

        // Check for Ns in seed
        if seed.iter().any(|&b| b == b'N' || b == b'n') {
            return Vec::new();
        }

        let hash = self.compute_hash(seed);
        let bucket_idx = (hash as usize) % self.config.num_buckets();

        // Read records from bucket
        let bucket_offset = bucket_idx * self.bucket_size;
        if bucket_offset + self.bucket_size > self.data.len() {
            return Vec::new();
        }

        let bucket_data = &self.data[bucket_offset..bucket_offset + self.bucket_size];

        // Parse hash records from bucket
        // Format: each record is 8 bytes (position + metadata)
        let mut positions = Vec::new();
        let mut offset = 0;

        while offset + 8 <= bucket_data.len() {
            let record =
                u64::from_le_bytes(bucket_data[offset..offset + 8].try_into().unwrap_or([0; 8]));

            if record == 0 {
                break; // Empty slot marks end of bucket
            }

            // Extract position from record
            // Lower bits are position, upper bits are metadata
            let pos = record & 0x0FFF_FFFF_FFFF; // 48 bits for position
            let is_reverse = (record >> 48) & 1 != 0;

            positions.push(RefPosition {
                seq_id: 0, // TODO: extract from position
                offset: pos,
                is_reverse,
            });

            offset += 8;

            // Limit results to avoid processing too many hits
            if positions.len() >= self.config.max_seed_freq as usize {
                break;
            }
        }

        positions
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hash_computation() {
        // Basic test that hash computation doesn't panic
        let config = HashTableConfig {
            version: 8,
            hash_table_bytes: 131072,
            pri_seed_bases: 18,
            max_seed_bases: 18,
            ref_seed_interval: 1.0,
            table_addr_bits: 17,
            max_seed_freq: 16,
            pri_crc_bits: 36,
            sec_crc_bits: 36,
            ref_seq_len: 1000,
            num_ref_seqs: 1,
            pri_crc_poly: 0x91A88EDCB,
            sec_crc_poly: 0x91A88EDCB,
        };

        let ht = HashTable {
            config,
            data: vec![0; 131072],
            bucket_size: 1,
        };

        let seed = b"ACGTACGTACGTACGTAC";
        let hash = ht.compute_hash(seed);
        assert!(hash > 0);
    }
}
